### ISSUE TITLE
name...

### ISSUE THREAD

**Issue by bsavery** [fedden/RenderMan#1]
FYI RenderMan is a tradermark of Pixar and the name of their 3D rendering software, been around for > 25 years.  Might want to rethink the name.

**Comment by fedden** [comment]
Hi there,

Yeah you are right. I had this pointed out to me a while back and initially dismissed it but on reflection I should change the name. I'm planning a rewrite with a host of new features so I will release it under a new name then.

Thanks for getting in touch! :)
